### ISSUE TITLE
Proposal 0016, Default Workflows

### ISSUE THREAD

**Issue by Belchy06** [tinkerbell/smee#178]
## Expected Behaviour

It would be very helpful to have default workflows for Tinkerbell, meaning that when a currently unknown machine sends out a DHCPDISCOVER request, Boots will push the new hardware and create a workflow for the new machine from the default template.

## Current Behaviour

Currently, you must manually push each new piece of hardware you expect and then manually create a workflow for this HW

## Possible Solution

on dhcpdiscover received:
	- grab mac address from req
	- create hardware with mac
        - push hardware
        - grab a template titled 'default'
	- create workflow with new hw id and `default` template id

## Context

Trying to provision multiple bare metal machines on a private network as soon as they are turned on

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):
Win10, Ubuntu

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:
Running based on [Local Setup with Vagrant](https://docs.tinkerbell.org/setup/local-vagrant/) tutorial

**Comment by displague** [comment]
In the 8/31 Tinkerbell meeting, this proposal was discussed briefly.  Some thoughts on the overall approach:

> - create hardware with mac
> - push hardware

Tinkerbell should avoid taking on more responsibilities.  A default workflow could take on this function.

> - grab a template titled 'default'
> - create workflow with new hw id and default template id

Workflows could be matched to hardware ID using some matching system rather than `==` comparisons.  
For example, one component of a matching system could be a regexp pattern.  A "Raspberry Pi Default Workflow" would match all Pi MAC Addresses (`B8:27:EB:.*`, https://www.wireshark.org/tools/oui-lookup.html).

Following that pattern, an 'AutoRegister Workflow' could match `.*` HW IDs.  Would we need to ensure that some default workflows are executed only once? Would we also need to set the priority of default workflows, enabling auto-register-workflow to run before raspberry-pi-workflow?

**Comment by jmpolom** [comment]
> Workflows could be matched to hardware ID using some matching system rather than == comparisons.
For example, one component of a matching system could be a regexp pattern. A "Raspberry Pi Default Workflow" could match all Pi MAC Addresses (B8:27:EB:.*, https://www.wireshark.org/tools/oui-lookup.html).
> 
> A more comprehensive matching system could take all hardware components into consideration.

I'm very interested in tinkerbell/boots gaining support to do "wildcard" hardware matching, initially just using a regex to match MAC addresses much like @displague provided as an example. I prefer the paradigm of creating workflows that can match a hardware identifier via some provided (regex) patterns, instead of only allowing a single "default" (both in name and function) template that is auto-registered to the specific hardware that is initially unknown to tinkerbell. I think this would be far more flexible and in effect create "scoped default workflows".

I think it should be left up to the user whether to run a workflow that explicitly registers a specific workflow per piece of hardware (ex: to [build an inventory](https://github.com/tinkerbell/boots/pull/179#issuecomment-916777710)) or simply allow workflows to run as they are matched to a specified identifier pattern. I do like the idea of having a "discovery" workflow that runs and is potentially able to gather much more system information than you receive from a simple DHCP request.

Am I correct in understanding that adding support for an enabling feature like regex matching of MAC addresses would need to be added to the tink server and not boots? Best I can tell from my read of the boots codebase is that boots does not do any hardware matching itself, except in the case of the standalone data model.

**Comment by mmlb** [comment]
We should discuss this in https://github.com/tinkerbell/tink/discussions/522. This is a tink feature not so much a boots one an as such doesn't make sense as an issue here.

**Comment by jacobweinstock** [comment]
Auto netboot capabilities in Smee have landed. https://github.com/tinkerbell/smee/pull/460 For auto capabilities with Workflows see the roadmap ticket: https://github.com/tinkerbell/roadmap/issues/23
